In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
a = np.array(5)

In [6]:
a


array(5)

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [13]:
a = np.array([1,2,3,5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [15]:
a[2]

np.int64(3)

In [16]:
pd.__version__

'2.3.2'

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])